satellites:
  LANDSAT_8:
    name: "Landsat 8"
    sensor: "OLI/TIRS"
    dataset_id: "LANDSAT/LC08/C02/T1_L2"
    bands:
      red: "SR_B4"
      nir: "SR_B5"
      cloud_mask: "QA_PIXEL"
      saturation_mask: "QA_RADSAT"
    scale_factors:
      optical: { multiplier: 0.0000275, offset: -0.2 }
      thermal: { multiplier: 0.00341802, offset: 149.0 }

  MODIS:
    name: "MODIS Terra"
    dataset_id: "MODIS/006/MOD13Q1"
    bands:
      ndvi: "NDVI"
      evi: "EVI"
    scale_factor: 0.0001
    resolution: 250
