project:
  ID: "sgrd-smart-farming"
  Name: "Smart Farming : research and development"
  Description: "Research and development of smart farming solutions for agriculture in syria."
  Version: "1.0.0"
  
